### PR TITLE
Allow to write in other Flash pages

### PR DESCRIPTION
**Pull request by fleborne**
I wanted to re-use Luos' function to write in Flash but at a different address than the one of the last page. The way `LuosHAL_FlashWriteLuosMemoryInfo` was implemented didn't allow me to do so, so I propose this modification that makes it possible.

### CODE REVIEW

**Comment by fleborne** [comment]
To make it possible to rewrite multiple times the same page of Flash, it is necessary to correctly erase this page before writing. I fixed that with commit 4a16354085535b944e021f400ebfae1f1e93afec but I don't have the necessary hardware to test a potential fix for G4 and L4 boards.

**Comment by nicolas-rabault** [comment]
On top of this modification we will have to add a Luos API allowing to access it. Users should never need to include LuosHAL in projects.

**Comment by nicolas-rabault** [comment]
After a long reflection about this subject, we don't really want to give access to flash through Luos because this is not the library's purpose.
But we start working on a bootloader, and we will need to have complete flash access in the LuosHAL for that.
@ncros3 will make this modification, but for now, we will not share the access to read/write flash through Luos.

**Comment by fleborne** [comment]
It makes sense. This code was a good example for a slightly different implementation but I agree with your point of view.

Regarding the bootloader, what do you mean by complete access? Read/write access to the required Flash pages for writing the firmware, or full read/write access to the whole Flash? How would it impact firmwares that use some pages of the Flash for other uses?

**Comment by nicolas-rabault** [comment]
It doesn't change anything regarding your usage of the flash. You just need to be sure your page is out of your binary space, but of course, we will try to avoid a complete erase of the entire flash each time.
We will make the flash usage similar to the DFU interface you are using now, avoiding erasing the page you use for configurations.

**Comment by assembly-lab** [comment]
Hello @fleborne, I implemented some HAL functions to write in FLASH for the bootloader. I don't know if this pull request is still relevant. I agree with @nicolas-rabault that if you want general access to the flash, you should use your own functions, Luos doesn't support general flash access for now.

If you agree with that, I will close this issue.

**Comment by fleborne** [comment]
It's alright for me, I also think this PR is not relevant anymore. Thanks!

**Pull request closed without merging**
