### PR TITLE
Rc 2.0.1

### PR DESCRIPTION
**Pull request by Salem-Tho**

### CODE REVIEW

**Review by BiliouriV — CHANGES_REQUESTED** [review]
Make sure that you dont put the timestamp commits in v2.0.1

**Review by BiliouriV — APPROVED** [review]

**Review by assembly-lab — APPROVED** [review]
It's ok for me.

**Review by nicolas-rabault — APPROVED** [review]
There is just some typo on commits comment.
Please take some time to just make them great 👍
Except that this is perfect.

**Comment by JeromeGalan** [comment]
OK,  typo on commits comments are corrected.
Ready to merge !

**Pull request merged**
